"""Argparse command tree for the Guardian CLI."""

from __future__ import annotations

"""Argument parser construction for the Guardian CLI.

Keeping parser wiring separate from command execution keeps `cli.py` focused on
dispatch and makes new plugin-facing commands easier to review.
"""

import argparse


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="guardian")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("init")

    diet = sub.add_parser("diet")
    diet_sub = diet.add_subparsers(dest="diet_command", required=True)
    diet_scan = diet_sub.add_parser("scan")
    diet_scan.add_argument("root", nargs="?", default=".")
    diet_scan.add_argument("--limit", type=int, default=50)
    diet_scan.add_argument("--usage-limit", type=int, default=8)
    diet_scan.add_argument("--json", action="store_true")

    project_scan = sub.add_parser("scan")
    project_scan.add_argument("root", nargs="?", default=".")
    project_scan.add_argument("--mode", choices=["daily", "standard", "deep", "handoff"], default="standard")
    project_scan.add_argument("--output", choices=["auto", "compact", "full"], default="auto")
    project_scan.add_argument("--max-seconds", type=int)
    project_scan.add_argument("--ecosystem", action="append", default=[])
    project_scan.add_argument("--include-installed", action="store_true")
    project_scan.add_argument("--include-ghsa", action="store_true")
    project_scan.add_argument("--ghsa-max-packages", type=int, default=50)
    project_scan.add_argument("--include-threat-intel", action="store_true")
    project_scan.add_argument("--include-openssf-malicious", action="store_true")
    project_scan.add_argument("--include-registry-intel", action="store_true")
    project_scan.add_argument("--threat-intel-severity-floor", choices=["unknown", "low", "medium", "high", "critical"], default="high")
    project_scan.add_argument("--handoff", action="store_true")
    project_scan.add_argument("--engine", choices=["auto", "guardian-native"])
    project_scan.add_argument("--json", action="store_true")

    daily_watch = sub.add_parser("daily-watch")
    daily_watch.add_argument("--root", action="append", default=[])
    daily_watch.add_argument("--ecosystem", action="append", default=[])
    daily_watch.add_argument("--include-installed", action="store_true")
    daily_watch.add_argument("--refresh-advisories", action="store_true")
    daily_watch.add_argument("--include-ghsa", action="store_true")
    daily_watch.add_argument("--ghsa-max-packages", type=int, default=50)
    daily_watch.add_argument("--live-enrichment", action="store_true")
    daily_watch.add_argument("--include-threat-intel", action="store_true")
    daily_watch.add_argument("--include-openssf-malicious", action="store_true")
    daily_watch.add_argument("--include-registry-intel", action="store_true")
    daily_watch.add_argument("--threat-intel-severity-floor", choices=["unknown", "low", "medium", "high", "critical"], default="high")
    daily_watch.add_argument("--engine", choices=["auto", "guardian-native"])
    daily_watch.add_argument("--json", action="store_true")

    repo_scout = sub.add_parser("repo-scout")
    repo_scout.add_argument("--repo", action="append", default=[], help="GitHub owner/name or github.com URL")
    repo_scout.add_argument("--repo-file", help="File containing one GitHub repo per line")
    repo_scout.add_argument("--scan-mode", choices=["daily", "standard", "deep"], default="standard")
    repo_scout.add_argument("--max-repos", type=int)
    repo_scout.add_argument("--per-repo-seconds", type=int, default=300)
    repo_scout.add_argument("--large-repo-seconds", type=int, default=900)
    repo_scout.add_argument("--total-seconds", type=int, default=1800)
    repo_scout.add_argument("--clone-timeout-seconds", type=int, default=120)
    repo_scout.add_argument("--include-installed", action="store_true")
    repo_scout.add_argument("--include-ghsa", action="store_true")
    repo_scout.add_argument("--ghsa-max-packages", type=int, default=40)
    repo_scout.add_argument("--include-threat-intel", action="store_true", default=True)
    repo_scout.add_argument("--no-threat-intel", dest="include_threat_intel", action="store_false")
    repo_scout.add_argument("--threat-intel-severity-floor", choices=["unknown", "low", "medium", "high", "critical"], default="high")
    repo_scout.add_argument("--high-signal-limit", type=int, default=10)
    repo_scout.add_argument("--skip-upstream-check", action="store_true", help="Disable GitHub duplicate and repo policy checks")
    repo_scout.add_argument("--keep-workdir", action="store_true")
    repo_scout.add_argument("--engine", choices=["auto", "guardian-native"])
    repo_scout.add_argument("--json", action="store_true")

    inventory = sub.add_parser("inventory")
    inventory_sub = inventory.add_subparsers(dest="inventory_command", required=True)
    scan = inventory_sub.add_parser("scan")
    scan.add_argument("--root", action="append", default=[])
    scan.add_argument("--ecosystem", action="append", default=[])
    scan.add_argument("--include-installed", action="store_true")
    scan.add_argument("--exclude", action="append", default=[])
    scan.add_argument("--engine", choices=["auto", "guardian-native"])
    scan.add_argument("--json", action="store_true")

    imp = inventory_sub.add_parser("import")
    imp.add_argument("--root", required=True)
    imp.add_argument("--ndjson", required=True)
    imp.add_argument("--json", action="store_true")

    assess = sub.add_parser("assess")
    assess_sub = assess.add_subparsers(dest="assess_command", required=True)
    refresh = assess_sub.add_parser("refresh")
    refresh.add_argument("--root", action="append", default=[])
    refresh.add_argument("--include-ghsa", action="store_true")
    refresh.add_argument("--ghsa-max-packages", type=int, default=50)
    refresh.add_argument("--json", action="store_true")

    daily = assess_sub.add_parser("run-daily")
    daily.add_argument("--root", action="append", default=[])
    daily.add_argument("--ecosystem", action="append", default=[])
    daily.add_argument("--include-installed", action="store_true")
    daily.add_argument("--include-ghsa", action="store_true")
    daily.add_argument("--ghsa-max-packages", type=int, default=50)
    daily.add_argument("--include-threat-intel", action="store_true")
    daily.add_argument("--threat-intel-severity-floor", choices=["unknown", "low", "medium", "high", "critical"])
    daily.add_argument("--engine", choices=["auto", "guardian-native"])
    daily.add_argument("--json", action="store_true")

    report = sub.add_parser("report")
    report_sub = report.add_subparsers(dest="report_command", required=True)
    summary_cmd = report_sub.add_parser("summary")
    summary_cmd.add_argument("--json", action="store_true")
    findings_cmd = report_sub.add_parser("findings")
    findings_cmd.add_argument("--json", action="store_true")
    issues_cmd = report_sub.add_parser("issues")
    issues_cmd.add_argument("--json", action="store_true")
    triage_cmd = report_sub.add_parser("triage")
    triage_cmd.add_argument("--root")
    triage_cmd.add_argument("--json", action="store_true")
    hygiene_cmd = report_sub.add_parser("hygiene")
    hygiene_cmd.add_argument("--root")
    hygiene_cmd.add_argument("--json", action="store_true")
    handoff_cmd = report_sub.add_parser("handoff")
    handoff_cmd.add_argument("--root", required=True)
    handoff_cmd.add_argument("--json", action="store_true")
    operator_cmd = report_sub.add_parser("operator")
    operator_cmd.add_argument("--root", required=True)
    operator_cmd.add_argument("--json", action="store_true")
    snapshot_cmd = report_sub.add_parser("snapshot")
    snapshot_cmd.add_argument("--root", required=True)
    snapshot_cmd.add_argument("--json", action="store_true")
    compare_cmd = report_sub.add_parser("compare")
    compare_cmd.add_argument("--root", required=True)
    compare_cmd.add_argument("--current-snapshot-id", type=int)
    compare_cmd.add_argument("--previous-snapshot-id", type=int)
    compare_cmd.add_argument("--json", action="store_true")
    remediation_cmd = report_sub.add_parser("remediation")
    remediation_cmd.add_argument("--root", required=True)
    remediation_cmd.add_argument("--limit", type=int, default=50)
    remediation_cmd.add_argument("--json", action="store_true")

    export = sub.add_parser("export")
    export_sub = export.add_subparsers(dest="export_command", required=True)
    export_catalog = export_sub.add_parser("exact-match-catalog")
    export_catalog.add_argument("--json", action="store_true")

    catalog = sub.add_parser("catalog")
    catalog_sub = catalog.add_subparsers(dest="catalog_command", required=True)
    catalog_verify = catalog_sub.add_parser("verify")
    catalog_verify.add_argument("--json", action="store_true")
    catalog_refresh = catalog_sub.add_parser("refresh")
    catalog_refresh.add_argument("--base-url")
    catalog_refresh.add_argument("--json", action="store_true")

    package_check = sub.add_parser("check-package")
    package_check.add_argument("ecosystem", choices=["npm", "pypi"])
    package_check.add_argument("name")
    package_check.add_argument("version", nargs="?")
    package_check.add_argument("--max-seconds", type=float)
    package_check.add_argument("--json", action="store_true")

    gate = sub.add_parser("gate")
    gate_sub = gate.add_subparsers(dest="gate_command", required=True)
    check = gate_sub.add_parser("check-package")
    check.add_argument("--ecosystem", required=True, choices=["npm", "pypi"])
    check.add_argument("--name", required=True)
    check.add_argument("--version", required=True)
    check.add_argument("--json", action="store_true")

    install = gate_sub.add_parser("install")
    install.add_argument("package_manager", choices=["npm", "pnpm", "pip"])
    install.add_argument("specs", nargs="+")
    install.add_argument("--execute", action="store_true")
    install.add_argument("--json", action="store_true")

    policy = sub.add_parser("policy")
    policy_sub = policy.add_subparsers(dest="policy_command", required=True)
    add_exc = policy_sub.add_parser("add-exception")
    add_exc.add_argument("--ecosystem", required=True)
    add_exc.add_argument("--name", required=True)
    add_exc.add_argument("--version")
    add_exc.add_argument("--action", required=True, choices=["allow", "warn", "block"])
    add_exc.add_argument("--reason", required=True)
    add_exc.add_argument("--expires-at")
    add_exc.add_argument("--created-by")
    add_exc.add_argument("--json", action="store_true")
    list_exc = policy_sub.add_parser("list-exceptions")
    list_exc.add_argument("--json", action="store_true")
    accept_name = policy_sub.add_parser("accept-name")
    accept_name.add_argument("ecosystem", choices=["npm", "pypi"])
    accept_name.add_argument("name")
    accept_name.add_argument("--reason", default="operator confirmed this package name")
    accept_name.add_argument("--created-by")
    accept_name.add_argument("--json", action="store_true")

    watchlist = sub.add_parser("watchlist")
    watchlist_sub = watchlist.add_subparsers(dest="watchlist_command", required=True)
    watch_run = watchlist_sub.add_parser("run")
    watch_run.add_argument("--path")
    watch_run.add_argument("--limit", type=int)
    watch_run.add_argument("--include-ghsa", action="store_true")
    watch_run.add_argument("--no-ghsa", action="store_true")
    watch_run.add_argument("--json", action="store_true")

    intel = sub.add_parser("intel")
    intel_sub = intel.add_subparsers(dest="intel_command", required=True)
    sources_init = intel_sub.add_parser("sources-init")
    sources_init.add_argument("--json", action="store_true")
    ingest = intel_sub.add_parser("ingest")
    ingest.add_argument("--source-config")
    ingest.add_argument("--root", action="append", default=[])
    ingest.add_argument("--ecosystem", action="append", default=[])
    ingest.add_argument("--severity-floor", choices=["unknown", "low", "medium", "high", "critical"])
    ingest.add_argument("--include-openssf-malicious", action="store_true")
    ingest.add_argument("--json", action="store_true")
    audit = intel_sub.add_parser("audit-parser")
    audit.add_argument("--source-dir", required=True)
    audit.add_argument("--json", action="store_true")

    validate = sub.add_parser("validate")
    validate_sub = validate.add_subparsers(dest="validate_command", required=True)
    plugin_release = validate_sub.add_parser("plugin-release")
    plugin_release.add_argument("--source-dir")
    plugin_release.add_argument("--json", action="store_true")

    return parser
